build:
	xbuild Hevadea.NoAndroid.sln

run:
	cd ./OpenGLPlatform/bin/DesktopGL/AnyCPU/Debug/;\
		mono ./OpenGLPlatform.exe

debug: 
	cd ./OpenGLPlatform/bin/DesktopGL/AnyCPU/Debug/;\
		mono --debug ./OpenGLPlatform.exe

buildAndrun: build run

buildAndDebug: build debug